name: React Native Web Build Test

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Hızlandırmak için cache ekledik

      - name: Install Dependencies
        run: npm install

      # Eğer Expo kullanıyorsan expo-cli gerekebilir
      - name: Setup Expo
        if: contains(github.event.head_commit.message, 'expo')
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest

      - name: Build Web Project
        run: npm run build # package.json'a eklediğimiz komut çalışacak

      - name: Upload Web Build Result
        uses: actions/upload-artifact@v4
        with:
          name: web-cikti-dosyalari
          # Expo web genelde 'web-build' veya 'dist' klasörüne çıktı verir
          path: web-build/ 
