name: Build and Package Only

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          npm install
          npm run build

      # İŞTE ASIL OLAY BURASI: Çıktıyı GitHub'a yükle
      - name: Upload Build Result
        uses: actions/upload-artifact@v4
        with:
          name: sitemin-cikti-dosyasi # İndireceğin dosyanın adı
          path: dist/ # Burayı projenin build klasörüne göre (dist veya build) ayarla
          retention-days: 5 # Dosyayı GitHub'da 5 gün saklar
